version: '3'
services:
  app:
    build:
      context: .
    ports:
      - 8000:80
    volumes:
      - .:/usr/src/app
      - ./demo/build:/usr/share/nginx/html:ro
      - ./conf/nginx.conf:/etc/nginx/sites-available/default
    working_dir: /usr/src/app/demo
    command:
    - /bin/bash
    - -c
    - |
      service nginx restart
      tail -f /dev/null 2>&1
    restart: on-failure